package cc.dkcms.cms.dao;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

    public static void mapping(ActiveRecordPlugin arp) {
        arp.addMapping("dao_account", "id", DaoAccount.class);


        arp.addMapping("dao_ad_category", "id", DaoAdCategory.class);
        arp.addMapping("dao_ad_position", "id", DaoAdPosition.class);
        arp.addMapping("dao_api_log", "id", DaoApiLog.class);
        arp.addMapping("dao_api_token", "id", DaoApiToken.class);
        arp.addMapping("dao_article", "id", DaoArticle.class);
        arp.addMapping("dao_category", "id", DaoCategory.class);
        arp.addMapping("dao_model", "id", DaoModel.class);
        arp.addMapping("dao_model_field", "id", DaoModelField.class);
        arp.addMapping("dao_role", "id", DaoRole.class);
        arp.addMapping("dao_setting", "id", DaoSetting.class);
        arp.addMapping("dao_single_page", "id", DaoSinglePage.class);
        arp.addMapping("dao_tag", "id", DaoTag.class);
        arp.addMapping("dao_comment", "id", DaoComment.class);
    }
}

