package cc.dkcms.cms.dao;

import cc.dkcms.cms.dao.base.BaseDaoApiToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DaoApiToken extends BaseDaoApiToken<DaoApiToken> {
    public final static DaoApiToken dao = new DaoApiToken().dao();

    public DaoApiToken getTokenByTokenString(String token) {
        return dao.findFirst("SELECT * FROM " + _getTable().getName() + " WHERE token =?", token);
    }
}
