package cc.dkcms.cms.dao;

import cc.dkcms.cms.dao.base.BaseDaoAdCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DaoAdCategory extends BaseDaoAdCategory<DaoAdCategory> {
    public final static DaoAdCategory dao = new DaoAdCategory().dao();

}
