package cc.dkcms.cms.dao;

import cc.dkcms.cms.dao.base.BaseDaoApiLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DaoApiLog extends BaseDaoApiLog<DaoApiLog> {
    public final static DaoApiLog dao = new DaoApiLog().dao();
}
