package cc.dkcms.cms.dao;

import cc.dkcms.cms.common.define.AccountType;
import cc.dkcms.cms.dao.base.BaseDaoAccount;
import com.jfinal.plugin.activerecord.Page;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DaoAccount extends BaseDaoAccount<DaoAccount> {

    public final static DaoAccount dao = new DaoAccount().dao();


    public Page<DaoAccount> getListByPage(int pageNo, int pageSize, AccountType role) {
        return dao.paginate(pageNo,
                pageSize,
                "select * ",
                " from " + _getTable().getName()
                        + " WHERE `role` = " + role.getVal()
                        + " order by id desc");
    }


    public List<DaoAccount> getAll() {
        return dao.findAll();
    }

    public DaoAccount getAccountByUsernameAndPassword(String username, String password) {
        return dao.findFirst(
                "select * from " + _getTable().getName() + " where username = ? and password = ?",
                username, password);
    }

    public boolean checkUsernameExist(String username) {
        DaoAccount account = dao.findFirst(
                "select * from " + _getTable().getName() + " where username = ? ",
                username);
        if (account != null) {
            return true;
        }
        return false;
    }
}