package cc.dkcms.cms.dao;

import cc.dkcms.cms.dao.base.BaseDaoAd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DaoAd extends BaseDaoAd<DaoAd> {
    public final static DaoAd dao = new DaoAd().dao();

}
