package cc.dkcms.cms.dao;

import cc.dkcms.cms.dao.base.BaseDaoModelField;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DaoModelField extends BaseDaoModelField<DaoModelField> {
    public final static DaoModelField dao = new DaoModelField().dao();


    public List<DaoModelField> getListByModelId(Integer modelId) {
        return dao.find("select * from " + _getTable().getName() + " where model_id = ?", modelId);
    }
}
