package cc.dkcms.cms.dao;

import cc.dkcms.cms.dao.base.BaseDaoModel;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DaoModel extends BaseDaoModel<DaoModel> {
    public final static DaoModel dao = new DaoModel().dao();

    public boolean checkExist(String name) {
        return Db.queryInt("select count(id) as cnt from "
                + _getTable().getName() + " where model_name = ?", name) > 0;
    }

    public Integer getIdByName(String name) {
        return Db.queryInt("select id from "
                + _getTable().getName() + " where model_name = ?", name);
    }
}
