package cc.dkcms.cms.dao;

import cc.dkcms.cms.common.Constant;
import cc.dkcms.cms.dao.base.BaseDaoSinglePage;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DaoSinglePage extends BaseDaoSinglePage<DaoSinglePage> {

    public static final DaoSinglePage dao = new DaoSinglePage().dao();

    public List<DaoSinglePage> getList() {
        return dao.find("select * from " + _getTable().getName() + " where is_delete = ?", Constant.FALSE);
    }
}
