package cc.dkcms.cms.dao;

import cc.dkcms.cms.dao.base.BaseDaoSetting;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DaoSetting extends BaseDaoSetting<DaoSetting> {
    public static final DaoSetting dao = new DaoSetting().dao();

    public DaoSetting getByKey(String key) {
        return dao.findFirst("select  * from " + _getTable().getName() + " where skey =?", key);

    }

    public List<DaoSetting> getAllDistinctByGroup() {
        return dao.find("select sgroup from " + _getTable().getName() + " group by sgroup");

    }
}
