package cc.dkcms.cms.dao.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDaoSetting<M extends BaseDaoSetting<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setSgroup(String sgroup) {
		set("sgroup", sgroup);
	}

	public String getSgroup() {
		return getStr("sgroup");
	}

	public void setSkey(String skey) {
		set("skey", skey);
	}

	public String getSkey() {
		return getStr("skey");
	}

	public void setSvalue(String svalue) {
		set("svalue", svalue);
	}

	public String getSvalue() {
		return getStr("svalue");
	}

	public void setSdefault(String sdefault) {
		set("sdefault", sdefault);
	}

	public String getSdefault() {
		return getStr("sdefault");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return getStr("name");
	}
	
}
