package cc.dkcms.cms.dao.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDaoAccount<M extends BaseDaoAccount<M>> extends Model<M> implements IBean {

    public void setId(Integer id) {
        set("id", id);
    }

    public Integer getId() {
        return getInt("id");
    }

    /**
     * 4-20个字符（汉字、字母、数字、下划线）
     */
    public void setUsername(String username) {
        set("username", username);
    }

    /**
     * 4-20个字符（汉字、字母、数字、下划线）
     */
    public String getUsername() {
        return getStr("username");
    }

    /**
     * 登录用户名
     */
    public void setPassword(String password) {
        set("password", password);
    }

    /**
     * 登录用户名
     */
    public String getPassword() {
        return getStr("password");
    }

    /**
     * 1正常，2禁用
     */
    public void setEnable(Boolean enable) {
        set("enable", enable);
    }

    /**
     * 1正常，2禁用
     */
    public Boolean getEnable() {
        return get("enable");
    }

    /**
     * 注册时间
     */
    public void setRegTime(java.util.Date regTime) {
        set("reg_time", regTime);
    }

    /**
     * 注册时间
     */
    public java.util.Date getRegTime() {
        return get("reg_time");
    }

    /**
     * 登录次数
     */
    public void setLoginTimes(Long loginTimes) {
        set("login_times", loginTimes);
    }

    /**
     * 登录次数
     */
    public Long getLoginTimes() {
        return getLong("login_times");
    }

    /**
     * 最后登录时间
     */
    public void setLastLoginAt(java.util.Date lastLoginAt) {
        set("last_login_at", lastLoginAt);
    }

    /**
     * 最后登录时间
     */
    public java.util.Date getLastLoginAt() {
        return get("last_login_at");
    }

    /**
     * 最后登录IP
     */
    public void setLastIp(String lastIp) {
        set("last_ip", lastIp);
    }

    /**
     * 最后登录IP
     */
    public String getLastIp() {
        return getStr("last_ip");
    }

    /**
     * 1普通 2 超级
     */
    public void setRole(Integer role) {
        set("role", role);
    }

    /**
     * 1普通 2 超级
     */
    public Integer getRole() {
        return getInt("role");
    }

    /**
     * 真名
     */
    public void setRealname(String realname) {
        set("realname", realname);
    }

    /**
     * 真名
     */
    public String getRealname() {
        return getStr("realname");
    }

    /**
     * 手机
     */
    public void setTelephone(String telephone) {
        set("telephone", telephone);
    }

    /**
     * 手机
     */
    public String getTelephone() {
        return getStr("telephone");
    }

    /**
     * 邮箱
     */
    public void setEmail(String email) {
        set("email", email);
    }

    /**
     * 邮箱
     */
    public String getEmail() {
        return getStr("email");
    }

    public void setGender(String gender) {
        set("gender", gender);
    }

    public String getGender() {
        return getStr("gender");
    }

    public void setAge(String age) {
        set("age", age);
    }

    public String getAge() {
        return getStr("age");
    }

    public void setCountry(String country) {
        set("country", country);
    }

    public String getCountry() {
        return getStr("country");
    }

    public void setProvince(String province) {
        set("province", province);
    }

    public String getProvince() {
        return getStr("province");
    }

    public void setCity(String city) {
        set("city", city);
    }

    public String getCity() {
        return getStr("city");
    }

    public void setCounty(String county) {
        set("county", county);
    }

    public String getCounty() {
        return getStr("county");
    }

    public void setLogo(String logo) {
        set("logo", logo);
    }

    public String getLogo() {
        return getStr("logo");
    }

    /**
     * 店长所在门店
     */
    public void setStoreId(Integer storeId) {
        set("store_id", storeId);
    }

    /**
     * 店长所在门店
     */
    public Integer getStoreId() {
        return getInt("store_id");
    }

}
