package cc.dkcms.cms.dao.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDaoCategory<M extends BaseDaoCategory<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setParentId(Integer parentId) {
		set("parent_id", parentId);
	}

	public Integer getParentId() {
		return getInt("parent_id");
	}

	/**
	 * 类型
	 */
	public void setCategoryType(Integer categoryType) {
		set("category_type", categoryType);
	}

	/**
	 * 类型
	 */
	public Integer getCategoryType() {
		return getInt("category_type");
	}

	public void setCategoryName(String categoryName) {
		set("category_name", categoryName);
	}

	public String getCategoryName() {
		return getStr("category_name");
	}

	public void setPermalink(String permalink) {
		set("permalink", permalink);
	}

	public String getPermalink() {
		return getStr("permalink");
	}

	public void setSort(Integer sort) {
		set("sort", sort);
	}

	public Integer getSort() {
		return getInt("sort");
	}

	public void setKeywords(String keywords) {
		set("keywords", keywords);
	}

	public String getKeywords() {
		return getStr("keywords");
	}

	public void setDescription(String description) {
		set("description", description);
	}

	public String getDescription() {
		return getStr("description");
	}

	public void setSeoDescription(String seoDescription) {
		set("seo_description", seoDescription);
	}

	public String getSeoDescription() {
		return getStr("seo_description");
	}

	/**
	 * 封面图
	 */
	public void setCoverImage(String coverImage) {
		set("cover_image", coverImage);
	}

	/**
	 * 封面图
	 */
	public String getCoverImage() {
		return getStr("cover_image");
	}

	/**
	 * 栏目模板
	 */
	public void setTemplateCate(String templateCate) {
		set("template_cate", templateCate);
	}

	/**
	 * 栏目模板
	 */
	public String getTemplateCate() {
		return getStr("template_cate");
	}

	/**
	 * 列表页面模板
	 */
	public void setTemplateList(String templateList) {
		set("template_list", templateList);
	}

	/**
	 * 列表页面模板
	 */
	public String getTemplateList() {
		return getStr("template_list");
	}

	/**
	 * 内容页面模板
	 */
	public void setTemplateContent(String templateContent) {
		set("template_content", templateContent);
	}

	/**
	 * 内容页面模板
	 */
	public String getTemplateContent() {
		return getStr("template_content");
	}

	/**
	 * 进入跳转
	 */
	public void setEnterPage(Integer enterPage) {
		set("enter_page", enterPage);
	}

	/**
	 * 进入跳转
	 */
	public Integer getEnterPage() {
		return getInt("enter_page");
	}

	/**
	 * 竖线分割的 tagid
	 */
	public void setTags(String tags) {
		set("tags", tags);
	}

	/**
	 * 竖线分割的 tagid
	 */
	public String getTags() {
		return getStr("tags");
	}

	/**
	 * 栏目主页内容
	 */
	public void setContent(String content) {
		set("content", content);
	}

	/**
	 * 栏目主页内容
	 */
	public String getContent() {
		return getStr("content");
	}

	public void setExtJson(String extJson) {
		set("ext_json", extJson);
	}

	public String getExtJson() {
		return getStr("ext_json");
	}
	
}
