package cc.dkcms.cms.dao.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDaoRole<M extends BaseDaoRole<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setRoleName(String roleName) {
		set("role_name", roleName);
	}

	public String getRoleName() {
		return getStr("role_name");
	}

	public void setRoleDesc(String roleDesc) {
		set("role_desc", roleDesc);
	}

	public String getRoleDesc() {
		return getStr("role_desc");
	}

	public void setIsEnable(Integer isEnable) {
		set("is_enable", isEnable);
	}

	public Integer getIsEnable() {
		return getInt("is_enable");
	}
	
}
