package cc.dkcms.cms.dao.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDaoAdCategory<M extends BaseDaoAdCategory<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setCategoryName(String categoryName) {
		set("category_name", categoryName);
	}

	public String getCategoryName() {
		return getStr("category_name");
	}
	
}
