package cc.dkcms.cms.dao.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDaoSinglePage<M extends BaseDaoSinglePage<M>> extends Model<M> implements IBean {

    public void setId(Integer id) {
        set("id", id);
    }

    public Integer getId() {
        return getInt("id");
    }

    public void setPermalink(String permalink) {
        set("permalink", permalink);
    }

    public String getPermalink() {
        return getStr("permalink");
    }

    public void setName(String name) {
        set("name", name);
    }

    public String getName() {
        return getStr("name");
    }

    public void setTemplate(String template) {
        set("template", template);
    }

    public String getTemplate() {
        return getStr("template");
    }

    public void setContent(String content) {
        set("content", content);
    }

    public String getContent() {
        return getStr("content");
    }

    public void setCreatedAt(java.util.Date createdAt) {
        set("created_at", createdAt);
    }

    public java.util.Date getCreatedAt() {
        return get("created_at");
    }

    public void setSeoKeywords(String seoKeywords) {
        set("seo_keywords", seoKeywords);
    }

    public String getSeoKeywords() {
        return getStr("seo_keywords");
    }

    public void setSeoDescription(String seoDescription) {
        set("seo_description", seoDescription);
    }

    public String getSeoDescription() {
        return getStr("seo_description");
    }

    public void setIsDelete(Integer isDelete) {
        set("is_delete", isDelete);
    }

    public Integer getIsDelete() {
        return getInt("is_delete");
    }

}
