package cc.dkcms.cms.dao.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDaoArticle<M extends BaseDaoArticle<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setPermalink(String permalink) {
		set("permalink", permalink);
	}

	public String getPermalink() {
		return getStr("permalink");
	}

	public void setCategoryId(Integer categoryId) {
		set("category_id", categoryId);
	}

	public Integer getCategoryId() {
		return getInt("category_id");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return getStr("title");
	}

	/**
	 * 发布时间
	 */
	public void setPublishDate(java.util.Date publishDate) {
		set("publish_date", publishDate);
	}

	/**
	 * 发布时间
	 */
	public java.util.Date getPublishDate() {
		return get("publish_date");
	}

	public void setContent(String content) {
		set("content", content);
	}

	public String getContent() {
		return getStr("content");
	}

	/**
	 * 摘要
	 */
	public void setSummary(String summary) {
		set("summary", summary);
	}

	/**
	 * 摘要
	 */
	public String getSummary() {
		return getStr("summary");
	}

	public void setTitleColor(String titleColor) {
		set("title_color", titleColor);
	}

	public String getTitleColor() {
		return getStr("title_color");
	}

	/**
	 * 点击量
	 */
	public void setClick(Integer click) {
		set("click", click);
	}

	/**
	 * 点击量
	 */
	public Integer getClick() {
		return getInt("click");
	}

	/**
	 * 推荐
	 */
	public void setIsRecommend(Integer isRecommend) {
		set("is_recommend", isRecommend);
	}

	/**
	 * 推荐
	 */
	public Integer getIsRecommend() {
		return getInt("is_recommend");
	}

	/**
	 * 是否前台显示
	 */
	public void setIsShow(Integer isShow) {
		set("is_show", isShow);
	}

	/**
	 * 是否前台显示
	 */
	public Integer getIsShow() {
		return getInt("is_show");
	}

	/**
	 * 是否进入回收站
	 */
	public void setIsDelete(Integer isDelete) {
		set("is_delete", isDelete);
	}

	/**
	 * 是否进入回收站
	 */
	public Integer getIsDelete() {
		return getInt("is_delete");
	}

	public void setKeywords(String keywords) {
		set("keywords", keywords);
	}

	public String getKeywords() {
		return getStr("keywords");
	}

	/**
	 * 封面配图
	 */
	public void setCoverImage(String coverImage) {
		set("cover_image", coverImage);
	}

	/**
	 * 封面配图
	 */
	public String getCoverImage() {
		return getStr("cover_image");
	}

	/**
	 * 作者
	 */
	public void setAuthor(String author) {
		set("author", author);
	}

	/**
	 * 作者
	 */
	public String getAuthor() {
		return getStr("author");
	}

	/**
	 * 来源
	 */
	public void setSource(String source) {
		set("source", source);
	}

	/**
	 * 来源
	 */
	public String getSource() {
		return getStr("source");
	}

	/**
	 * 发布管理员id
	 */
	public void setManagerId(Integer managerId) {
		set("manager_id", managerId);
	}

	/**
	 * 发布管理员id
	 */
	public Integer getManagerId() {
		return getInt("manager_id");
	}

	public void setExtJson(String extJson) {
		set("ext_json", extJson);
	}

	public String getExtJson() {
		return getStr("ext_json");
	}

	/**
	 * 逗号分割的tagId
	 */
	public void setTags(String tags) {
		set("tags", tags);
	}

	/**
	 * 逗号分割的tagId
	 */
	public String getTags() {
		return getStr("tags");
	}

	public void setSort(Integer sort) {
		set("sort", sort);
	}

	public Integer getSort() {
		return getInt("sort");
	}
	
}
