package cc.dkcms.cms.dao.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDaoApiToken<M extends BaseDaoApiToken<M>> extends Model<M> implements IBean {

    public void setId(Integer id) {
        set("id", id);
    }

    public Integer getId() {
        return getInt("id");
    }

    public void setToken(String token) {
        set("token", token);
    }

    public String getToken() {
        return getStr("token");
    }

    public void setName(String name) {
        set("name", name);
    }

    public String getName() {
        return getStr("name");
    }

    public void setCreatedAt(java.util.Date createdAt) {
        set("created_at", createdAt);
    }

    public java.util.Date getCreatedAt() {
        return get("created_at");
    }

    public void setExpiredAt(java.util.Date expiredAt) {
        set("expired_at", expiredAt);
    }

    public java.util.Date getExpiredAt() {
        return get("expired_at");
    }

    public void setIsValid(Integer isValid) {
        set("is_valid", isValid);
    }

    public Integer getIsValid() {
        return getInt("is_valid");
    }

    public void setManagerId(Integer managerId) {
        set("manager_id", managerId);
    }

    public Integer getManagerId() {
        return getInt("manager_id");
    }

}
