package cc.dkcms.cms.dao.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDaoAdPosition<M extends BaseDaoAdPosition<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setCategoryId(Integer categoryId) {
		set("category_id", categoryId);
	}

	public Integer getCategoryId() {
		return getInt("category_id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return getStr("name");
	}

	public void setDescription(String description) {
		set("description", description);
	}

	public String getDescription() {
		return getStr("description");
	}

	public void setWidth(Integer width) {
		set("width", width);
	}

	public Integer getWidth() {
		return getInt("width");
	}

	public void setHeight(Integer height) {
		set("height", height);
	}

	public Integer getHeight() {
		return getInt("height");
	}

	public void setContent(String content) {
		set("content", content);
	}

	public String getContent() {
		return getStr("content");
	}

	public void setIsValid(Boolean isValid) {
		set("is_valid", isValid);
	}

	public Boolean getIsValid() {
		return get("is_valid");
	}

	public void setContentInvalid(String contentInvalid) {
		set("content_invalid", contentInvalid);
	}

	public String getContentInvalid() {
		return getStr("content_invalid");
	}

	public void setContentImage(String contentImage) {
		set("content_image", contentImage);
	}

	public String getContentImage() {
		return getStr("content_image");
	}
	
}
